const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const socket = io({ transports: ['websocket','polling'] });
let W=innerWidth,H=innerHeight,dpr=1,myId=null,joined=false,dead=false,state=null,selectedSkin='aurora';
let camera={x:0,y:0,zoom:1}, pointer={x:0,y:0,active:false}, boost=false, lastInput=0;
const els={menu:q('#menu'),skins:q('#skins'),play:q('#play'),name:q('#name'),hud:q('#hud'),score:q('#score'),length:q('#length'),leaders:q('#leaders'),board:q('#leaderboard'),boost:q('#boost'),dead:q('#dead'),deathText:q('#deathText'),again:q('#again'),home:q('#home'),serverCount:q('#serverCount'),hudCount:q('#hudCount')};
function q(s){return document.querySelector(s)}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const fallbackSkins=[['aurora',['#00f5ff','#7c3cff','#ff4ecd']],['citrus',['#fff95b','#ff9f1c','#2ec4b6']],['berry',['#ff4ecd','#9b5de5','#00bbf9']],['mint',['#80ffdb','#48bfe3','#64dfdf']],['lava',['#ff3c38','#ff8c42','#ffd166']],['cosmic',['#f72585','#7209b7','#3a0ca3']]];
function renderSkins(skins=fallbackSkins.map(([id,colors])=>({id,colors}))){els.skins.innerHTML='';skins.forEach(s=>{const b=document.createElement('button');b.className='skin '+(s.id===selectedSkin?'active':'');b.style.setProperty('--a',s.colors[0]);b.style.setProperty('--b',s.colors[1]);b.style.setProperty('--c',s.colors[2]);b.title=s.id;b.onclick=()=>{selectedSkin=s.id;renderSkins(skins)};els.skins.appendChild(b)})}renderSkins();
socket.on('serverInfo',info=>{els.serverCount.textContent=`${info.count}/${info.max}`;els.hudCount.textContent=`${info.count}/${info.max}`; if(info.skins) renderSkins(info.skins)});
socket.on('joined',data=>{myId=data.id;joined=true;dead=false;els.menu.classList.add('hidden');els.dead.classList.add('hidden');els.hud.classList.remove('hidden');els.board.classList.remove('hidden');els.boost.classList.remove('hidden')});
socket.on('full',d=>alert(d.message||'Server is full.'));
socket.on('dead',d=>{dead=true;els.deathText.textContent=`Final score: ${d.score||0}${d.killerName?' · Hit '+d.killerName:''}`;els.dead.classList.remove('hidden')});
socket.on('state',s=>{state=s;els.serverCount.textContent=`${s.count}/${s.max}`;els.hudCount.textContent=`${s.count}/${s.max}`;const me=s.players.find(p=>p.id===myId);if(me){els.score.textContent=me.score;els.length.textContent=me.length}els.leaders.innerHTML=s.leaderboard.map(p=>`<li>${escapeHtml(p.name)} <b>${p.score}</b></li>`).join('')});
function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
els.play.onclick=()=>socket.emit('join',{name:els.name.value||'Player',skin:selectedSkin});els.again.onclick=()=>socket.emit('respawn',{name:els.name.value||'Player',skin:selectedSkin});els.home.onclick=()=>{els.dead.classList.add('hidden');els.menu.classList.remove('hidden')};
addEventListener('pointerdown',e=>{pointer.active=true;pointer.x=e.clientX;pointer.y=e.clientY});addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});addEventListener('pointerup',()=>pointer.active=false);addEventListener('keydown',e=>{if(e.code==='Space')boost=true});addEventListener('keyup',e=>{if(e.code==='Space')boost=false});['pointerdown','touchstart'].forEach(ev=>els.boost.addEventListener(ev,e=>{e.preventDefault();boost=true}));['pointerup','touchend','touchcancel','pointercancel'].forEach(ev=>els.boost.addEventListener(ev,e=>{e.preventDefault();boost=false}));
function sendInput(){if(!joined||dead||!state)return;const me=state.players.find(p=>p.id===myId);if(!me)return;let sx=W/2,sy=H/2;if(pointer.active){sx=pointer.x;sy=pointer.y}else if(matchMedia('(hover:hover)').matches){sx=pointer.x||W/2+Math.cos(me.angle)*100;sy=pointer.y||H/2+Math.sin(me.angle)*100}const angle=Math.atan2(sy-H/2,sx-W/2);const now=performance.now();if(now-lastInput>33){socket.emit('input',{angle,boost});lastInput=now}}setInterval(sendInput,25);
function worldToScreen(x,y){return{x:(x-camera.x)*camera.zoom+W/2,y:(y-camera.y)*camera.zoom+H/2}}
function drawGrid(map){const step=260;ctx.strokeStyle='rgba(255,255,255,.045)';ctx.lineWidth=1;for(let x=-map/2;x<=map/2;x+=step){const a=worldToScreen(x,-map/2),b=worldToScreen(x,map/2);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let y=-map/2;y<=map/2;y+=step){const a=worldToScreen(-map/2,y),b=worldToScreen(map/2,y);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}const tl=worldToScreen(-map/2,-map/2),br=worldToScreen(map/2,map/2);ctx.strokeStyle='rgba(255,78,205,.65)';ctx.lineWidth=5;ctx.strokeRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y)}
function drawFood(f,t){const p=worldToScreen(f.x,f.y);const r=(5+f.value*1.4+Math.sin(t/280+f.pulse)*1.2)*camera.zoom;ctx.save();ctx.shadowBlur=16;ctx.shadowColor=`hsl(${f.hue},100%,65%)`;ctx.fillStyle=`hsl(${f.hue},100%,64%)`;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawWorm(p){const segs=p.segments;if(!segs.length)return;ctx.lineCap='round';ctx.lineJoin='round';for(let layer=0;layer<2;layer++){ctx.beginPath();segs.forEach((s,i)=>{const v=worldToScreen(s.x,s.y);i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y)});ctx.lineWidth=(layer?18:28)*camera.zoom;ctx.strokeStyle=layer?gradientFor(p):'rgba(0,0,0,.28)';ctx.shadowBlur=layer&&p.boost?28:12;ctx.shadowColor=p.colors[1];ctx.stroke()}const h=worldToScreen(p.x,p.y);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(h.x+Math.cos(p.angle-.45)*8*camera.zoom,h.y+Math.sin(p.angle-.45)*8*camera.zoom,3.2*camera.zoom,0,7);ctx.arc(h.x+Math.cos(p.angle+.45)*8*camera.zoom,h.y+Math.sin(p.angle+.45)*8*camera.zoom,3.2*camera.zoom,0,7);ctx.fill();ctx.font='800 13px Inter,Arial';ctx.textAlign='center';ctx.fillStyle='rgba(255,255,255,.9)';ctx.fillText(p.name,h.x,h.y-28*camera.zoom)}
function gradientFor(p){const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,p.colors[0]);g.addColorStop(.5,p.colors[1]);g.addColorStop(1,p.colors[2]);return g}
function render(t=0){ctx.clearRect(0,0,W,H);ctx.fillStyle='#070817';ctx.fillRect(0,0,W,H);if(state){const me=state.players.find(p=>p.id===myId);if(me){camera.x+=(me.x-camera.x)*.12;camera.y+=(me.y-camera.y)*.12;camera.zoom+=(Math.max(.62,1.05-me.length/460)-camera.zoom)*.05}drawGrid(state.mapSize);state.foods.forEach(f=>drawFood(f,t));state.players.sort((a,b)=>a.length-b.length).forEach(drawWorm)}else{ctx.fillStyle='rgba(255,255,255,.06)';for(let i=0;i<80;i++){ctx.beginPath();ctx.arc((i*97+t*.02)%W,(i*173)%H,2+(i%5),0,7);ctx.fill()}}requestAnimationFrame(render)}render();
