const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000, WORLD=5200, MAX=15, TICK=30, SNAP=15;
const sendFile=(res,file,type)=>fs.readFile(path.join(__dirname,file),(e,d)=>{res.writeHead(e?404:200,{'Content-Type':e?'text/plain':type,'Cache-Control':'no-store'});res.end(e?'not found':d)});
const srv=http.createServer((req,res)=>sendFile(res,'index.html','text/html; charset=utf-8'));
const arenas=[newArena()];
function newArena(){return{players:new Map(),food:[],lastSnap:0};}
function rnd(n){return Math.random()*n} function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function dist(a,b,c,d){return Math.hypot(a-c,b-d)}
function addFood(ar,n){while(ar.food.length<n)ar.food.push({x:rnd(WORLD),y:rnd(WORLD),r:5+rnd(6),c:Math.floor(rnd(360)),v:1})}
function spawn(p){let x=400+rnd(WORLD-800),y=400+rnd(WORLD-800);Object.assign(p,{x,y,a:rnd(Math.PI*2),ta:rnd(Math.PI*2),boost:false,alive:true,score:80,deadAt:0,trail:[]});for(let i=0;i<80;i++)p.trail.push({x:x-Math.cos(p.a)*i*9,y:y-Math.sin(p.a)*i*9});}
function pickArena(){let ar=arenas.find(a=>[...a.players.values()].filter(p=>p.alive).length<MAX);if(!ar){ar=newArena();arenas.push(ar)}return ar}
function pack(ar){return JSON.stringify({t:'state',world:WORLD,alive:[...ar.players.values()].filter(p=>p.alive).length,max:MAX,food:ar.food,players:[...ar.players.values()].filter(p=>p.alive).map(p=>({id:p.id,name:p.name,skin:p.skin,x:p.x,y:p.y,a:p.a,score:Math.floor(p.score),trail:p.trail.filter((_,i)=>i%2===0)}))})}
function drop(ar,x,y,c,n=1){for(let i=0;i<n;i++)ar.food.push({x:x+rnd(34)-17,y:y+rnd(34)-17,r:6+rnd(4),c:c||Math.floor(rnd(360)),v:2})}
function die(ar,p){if(!p.alive)return;p.alive=false;p.deadAt=Date.now();for(let i=0;i<p.trail.length;i+=4)drop(ar,p.trail[i].x,p.trail[i].y,p.skin==='dog'?28:Math.floor(rnd(360)),1)}
function angleTurn(a,t,max){let d=((t-a+Math.PI*3)%(Math.PI*2))-Math.PI;return a+clamp(d,-max,max)}
function step(){for(const ar of arenas){addFood(ar,260);for(const p of ar.players.values()){if(!p.alive){if(Date.now()-p.deadAt>1800)spawn(p);continue}p.a=angleTurn(p.a,p.ta,0.14);let boost=p.boost&&p.score>24;let speed=boost?8.2:5.6;p.x+=Math.cos(p.a)*speed;p.y+=Math.sin(p.a)*speed;if(p.x<24||p.y<24||p.x>WORLD-24||p.y>WORLD-24){die(ar,p);continue}p.trail.unshift({x:p.x,y:p.y});let maxLen=Math.max(22,Math.floor(p.score*1.42));while(p.trail.length>maxLen)p.trail.pop();if(boost){p.score=Math.max(20,p.score-.32);let tail=p.trail[p.trail.length-1]; if(tail&&Math.random()<.72)drop(ar,tail.x,tail.y,p.skin==='dog'?28:180,1);}
for(let i=ar.food.length-1;i>=0;i--){let f=ar.food[i];if(dist(p.x,p.y,f.x,f.y)<23+f.r){p.score+=f.v?2.8:1.8;ar.food.splice(i,1)}}
for(const o of ar.players.values()){if(!o.alive||o.id===p.id)continue;for(let i=8;i<o.trail.length;i+=3){let q=o.trail[i];if(dist(p.x,p.y,q.x,q.y)<22){die(ar,p);break}}if(!p.alive)break;}}
if(Date.now()-ar.lastSnap>1000/SNAP){ar.lastSnap=Date.now();let msg=pack(ar);for(const p of ar.players.values())if(p.ws&&p.ws.readyState===1)p.ws.send(msg)}}}
setInterval(step,1000/TICK);
function frame(op,payload){const b=Buffer.from(payload);let h;if(b.length<126){h=Buffer.from([0x81,b.length])}else{h=Buffer.alloc(4);h[0]=0x81;h[1]=126;h.writeUInt16BE(b.length,2)}return Buffer.concat([h,b])}
function decode(buf){let len=buf[1]&127,off=2;if(len===126){len=buf.readUInt16BE(2);off=4}else if(len===127)return null;let mask=buf.slice(off,off+4);off+=4;let out=Buffer.alloc(len);for(let i=0;i<len;i++)out[i]=buf[off+i]^mask[i%4];return out.toString()}
srv.on('upgrade',(req,socket)=>{if(req.headers.upgrade!=='websocket'){socket.destroy();return}let key=req.headers['sec-websocket-key'];let accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');socket.readyState=1;socket.send=s=>socket.write(frame(1,s));let ar=pickArena(),p={id:crypto.randomBytes(4).toString('hex'),name:'Player',skin:'aqua',ws:socket};ar.players.set(p.id,p);spawn(p);socket.send(JSON.stringify({t:'hello',id:p.id,alive:[...ar.players.values()].filter(x=>x.alive).length,max:MAX}));socket.on('data',buf=>{try{let m=JSON.parse(decode(buf)||'{}');if(m.t==='join'){p.name=String(m.name||'Player').slice(0,14);p.skin=String(m.skin||'aqua').slice(0,12)}if(m.t==='input'){p.ta=Number(m.a)||p.ta;p.boost=!!m.boost}if(m.t==='home'){ar.players.delete(p.id);socket.end()}}catch(e){}});socket.on('close',()=>ar.players.delete(p.id));socket.on('error',()=>ar.players.delete(p.id));});
srv.listen(PORT,()=>console.log('Slither Pro Advanced running on '+PORT));
